version: '3.8'

services:
  mycodecombat:
    image: operepo/ope-codecombat
    container_name: codecombat
    restart: always
    volumes:
      - ./data:/home/coco/codecombat/data/
      - ./mongo:/home/coco/codecombat/mongo
      - ./patch/server_setup.coffee:/home/coco/codecombat/server_setup.coffee
    ports:
      - "3020:3000"
